In [147]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import numpy as np

In [149]:
df = pd.read_csv('2024 pbp 11.40.43â€¯AM/wnba_playbyplay_1022400001.csv')
df['homePlayer1'] = 0
df['homePlayer2'] = 0
df['homePlayer3'] = 0
df['homePlayer4'] = 0
df['homePlayer5'] = 0
df['awayPlayer1'] = 0
df['awayPlayer2'] = 0
df['awayPlayer3'] = 0
df['awayPlayer4'] = 0
df['awayPlayer5'] = 0
df.head()

,game_clock,description,location_x,location_y,event_type,opp_player_id,player_id,sec_player_id,team_id,home_score,away_score,points,period,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,awayPlayer1,awayPlayer2,awayPlayer3,awayPlayer4,awayPlayer5
0,10:00,Start Period,0,-80,12,NaN,0,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,09:57,Jump Ball Jones vs Austin (Vandersloot gains p...,0,-80,10,1631022.0,1627673,202664.0,1611661313,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,09:56,[NYL] Vandersloot Turnover : Out of Bounds - B...,115,344,5,NaN,202664,1629177.0,1611661313,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,09:45,[WAS] Atkins Pullup Jump shot: Missed,-135,35,2,NaN,1628878,NaN,1611661322,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,09:42,[NYL] Jones Rebound (Off:0 Def:1),-135,35,4,NaN,1627673,NaN,1611661313,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [151]:
df['homeTeam'] = df.loc[list(df[df['home_score'] != 0].index)[0], 'team_id']
df['awayTeam'] = df.loc[list(df[df['away_score'] != 0].index)[0], 'team_id']
df.head()

,game_clock,description,location_x,location_y,event_type,opp_player_id,player_id,sec_player_id,team_id,home_score,away_score,points,period,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,awayPlayer1,awayPlayer2,awayPlayer3,awayPlayer4,awayPlayer5,homeTeam,awayTeam
0,10:00,Start Period,0,-80,12,NaN,0,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313
1,09:57,Jump Ball Jones vs Austin (Vandersloot gains p...,0,-80,10,1631022.0,1627673,202664.0,1611661313,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313
2,09:56,[NYL] Vandersloot Turnover : Out of Bounds - B...,115,344,5,NaN,202664,1629177.0,1611661313,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313
3,09:45,[WAS] Atkins Pullup Jump shot: Missed,-135,35,2,NaN,1628878,NaN,1611661322,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313
4,09:42,[NYL] Jones Rebound (Off:0 Def:1),-135,35,4,NaN,1627673,NaN,1611661313,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313

In [153]:
dfTeam1 = df[df['team_id'] == df['homeTeam']]
dfTeam1.head()

,game_clock,description,location_x,location_y,event_type,opp_player_id,player_id,sec_player_id,team_id,home_score,away_score,points,period,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,awayPlayer1,awayPlayer2,awayPlayer3,awayPlayer4,awayPlayer5,homeTeam,awayTeam
3,09:45,[WAS] Atkins Pullup Jump shot: Missed,-135,35,2,NaN,1628878,NaN,1611661322,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313
6,09:19,[WAS 2-2] Austin Driving Layup Shot: Made (2 P...,-49,24,1,NaN,1631022,1628279.0,1611661322,2,2,2,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313
8,09:19,[WAS] Austin Free Throw 1 of 1 Missed,0,-80,3,NaN,1631022,NaN,1611661322,2,2,0,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313
11,08:58,[WAS 5-4] Atkins 3pt Shot: Made (3 PTS) Assist...,-238,-42,1,NaN,1628878,203828.0,1611661322,5,4,3,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313
16,08:33,[WAS] Austin Rebound (Off:0 Def:1),2,49,4,NaN,1631022,NaN,1611661322,5,4,0,1,0,0,0,0,0,0,0,0,0,0,1611661322,1611661313

In [155]:
alreadyScenePlayer = []
for playerID in dfTeam1.loc[:list(dfTeam1[dfTeam1['event_type'] == 8].index)[0] - 1, :]['player_id']:
    if playerID not in alreadyScenePlayer:
        if (dfTeam1.loc[:list(dfTeam1[dfTeam1['event_type'] == 8].index)[0] - 1, :]['homePlayer1'] == 0).any():
            dfTeam1['homePlayer1'] = playerID
        elif (dfTeam1.loc[:list(dfTeam1[dfTeam1['event_type'] == 8].index)[0] - 1, :]['homePlayer2'] == 0).any():
            dfTeam1['homePlayer2'] = playerID
        elif (dfTeam1.loc[:list(dfTeam1[dfTeam1['event_type'] == 8].index)[0] - 1, :]['homePlayer3'] == 0).any():
            dfTeam1['homePlayer3'] = playerID
        elif (dfTeam1.loc[:list(dfTeam1[dfTeam1['event_type'] == 8].index)[0] - 1, :]['homePlayer4'] == 0).any():
            dfTeam1['homePlayer4'] = playerID
        elif (dfTeam1.loc[:list(dfTeam1[dfTeam1['event_type'] == 8].index)[0] - 1, :]['homePlayer5'] == 0).any():
            dfTeam1['homePlayer5'] = playerID

        alreadyScenePlayer.append(playerID)

dfTeam1.head()

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_17992/3210203819.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTeam1['homePlayer1'] = playerID
/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_17992/3210203819.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTeam1['homePlayer2'] = playerID
/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_17992/3210203819.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTeam1['homePlayer3'] = playerID
/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_17992/3210203819.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTeam1['homePlayer4'] = playerID

,game_clock,description,location_x,location_y,event_type,opp_player_id,player_id,sec_player_id,team_id,home_score,away_score,points,period,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,awayPlayer1,awayPlayer2,awayPlayer3,awayPlayer4,awayPlayer5,homeTeam,awayTeam
3,09:45,[WAS] Atkins Pullup Jump shot: Missed,-135,35,2,NaN,1628878,NaN,1611661322,0,0,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
6,09:19,[WAS 2-2] Austin Driving Layup Shot: Made (2 P...,-49,24,1,NaN,1631022,1628279.0,1611661322,2,2,2,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
8,09:19,[WAS] Austin Free Throw 1 of 1 Missed,0,-80,3,NaN,1631022,NaN,1611661322,2,2,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
11,08:58,[WAS 5-4] Atkins 3pt Shot: Made (3 PTS) Assist...,-238,-42,1,NaN,1628878,203828.0,1611661322,5,4,3,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
16,08:33,[WAS] Austin Rebound (Off:0 Def:1),2,49,4,NaN,1631022,NaN,1611661322,5,4,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313

In [157]:
dfTeam1.iloc[:, 9:]

,home_score,away_score,points,period,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,awayPlayer1,awayPlayer2,awayPlayer3,awayPlayer4,awayPlayer5,homeTeam,awayTeam
3,0,0,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
6,2,2,2,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
8,2,2,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
11,5,4,3,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
16,5,4,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
18,5,4,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
21,8,6,3,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
23,11,8,3,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
25,11,8,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
26,11,8,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
29,13,10,2,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
31,13,10,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
32,13,10,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
33,13,10,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
34,13,10,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
37,13,13,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
40,13,13,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
43,13,13,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
46,13,13,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
49,15,13,2,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
51,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
52,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
54,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
57,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
58,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
59,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
60,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
61,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
62,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
63,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
67,15,18,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
68,15,18,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
69,15,18,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
72,15,18,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
73,15,18,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
74,15,18,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
77,18,20,3,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
79,20,23,2,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
80,20,23,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
81,20,23,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
87,20,23,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
89,20,23,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
90,20,23,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
91,20,23,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
94,20,23,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
96,20,23,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
98,22,25,2,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
100,22,27,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
101,22,27,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
103,22,27,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
107,22,27,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
111,23,27,1,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
112,24,27,1,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
114,24,29,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
115,24,29,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
116,24,29,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
120,24,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
121,24,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
124,25,31,1,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
125,26,31,1,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
127,26,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
128,26,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
130,26,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
131,28,31,2,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
133,28,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
137,28,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
139,28,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
142,30,34,2,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
143,30,34,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
144,30,34,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
145,30,34,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
147,30,36,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
149,30,36,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
152,30,36,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
154,30,38,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
155,30,38,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
157,30,39,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
161,30,39,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
164,30,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
165,30,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
167,30,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
169,30,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
170,30,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
171,30,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
173,31,40,1,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
175,33,40,2,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
177,35,40,2,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
179,35,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
180,35,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
183,35,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
184,38,40,3,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
186,38,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
191,38,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
193,39,40,1,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
195,40,40,1,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
200,40,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
201,43,40,3,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
207,43,40,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
209,43,40,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
211,43,42,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
213,43,43,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
218,45,43,2,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
220,45,46,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
223,45,46,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
224,48,46,3,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
228,48,46,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
229,50,46,2,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
231,52,48,2,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
233,52,48,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
234,54,48,2,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
236,54,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
237,54,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
239,54,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
240,54,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
241,54,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
244,54,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
245,56,51,2,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
248,56,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
251,58,51,2,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
255,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
256,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
259,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
260,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
264,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
265,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
269,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
270,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
273,58,53,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
278,58,55,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
279,58,55,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
280,61,55,3,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
281,61,55,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
283,61,56,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
286,61,57,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
288,64,59,3,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
290,64,59,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
291,64,59,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
292,64,59,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
296,67,59,3,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
300,67,59,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
302,67,59,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
304,67,59,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
306,69,61,2,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
308,69,64,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
309,69,64,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
311,69,64,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
312,69,64,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
313,69,64,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
316,69,64,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
319,69,65,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
320,71,65,2,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
322,71,68,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
324,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
325,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
326,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
327,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
330,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
333,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
334,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
335,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
336,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
338,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
340,71,72,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
341,71,72,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
345,71,74,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
347,71,75,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
348,71,75,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
350,71,75,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
351,71,75,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
352,72,75,1,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
355,72,75,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
356,72,75,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
361,74,77,2,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
362,74,77,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
364,74,77,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
365,74,77,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
367,74,79,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
368,74,79,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
369,74,79,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
371,76,81,2,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
374,78,81,2,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
378,80,81,2,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
380,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
381,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
386,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
389,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
390,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
391,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
392,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
393,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
394,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
397,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
398,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
399,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
401,80,82,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
402,80,82,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
404,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
405,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
406,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
410,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
411,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
412,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
413,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
415,80,84,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313

In [159]:
dfTeam1[dfTeam1['event_type'] == 8]

,game_clock,description,location_x,location_y,event_type,opp_player_id,player_id,sec_player_id,team_id,home_score,away_score,points,period,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,awayPlayer1,awayPlayer2,awayPlayer3,awayPlayer4,awayPlayer5,homeTeam,awayTeam
31,06:00,[WAS] Austin Substitution replaced by Hines-Allen,0,-80,8,NaN,1631022,1628899.0,1611661322,13,10,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
43,04:53,[WAS] Atkins Substitution replaced by Vanloo,0,-80,8,NaN,1628878,1642210.0,1611661322,13,13,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
63,03:13,[WAS] Dolson Substitution replaced by Edwards,0,-80,8,NaN,203828,1642290.0,1611661322,15,16,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
67,02:42,[WAS] Sykes Substitution replaced by Walker-Ki...,0,-80,8,NaN,1628279,1628278.0,1611661322,15,18,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
68,02:42,[WAS] Samuelson Substitution replaced by Atkins,0,-80,8,NaN,1628317,1628878.0,1611661322,15,18,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
81,00:51.7,[WAS] Hines-Allen Substitution replaced by Austin,0,-80,8,NaN,1628899,1631022.0,1611661322,20,23,0,1,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
120,07:20,[WAS] Austin Substitution replaced by Sykes,0,-80,8,NaN,1631022,1628279.0,1611661322,24,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
121,07:20,[WAS] Vanloo Substitution replaced by Dolson,0,-80,8,NaN,1642210,203828.0,1611661322,24,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
133,06:17,[WAS] Edwards Substitution replaced by Hines-A...,0,-80,8,NaN,1642290,1628899.0,1611661322,28,31,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
144,05:04,[WAS] Atkins Substitution replaced by Samuelson,0,-80,8,NaN,1628878,1628317.0,1611661322,30,34,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
145,05:04,[WAS] Walker-Kimbrough Substitution replaced b...,0,-80,8,NaN,1628278,1630459.0,1611661322,30,34,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
171,02:58,[WAS] Richards Substitution replaced by Atkins,0,-80,8,NaN,1630459,1628878.0,1611661322,30,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
186,01:26,[WAS] Hines-Allen Substitution replaced by Austin,0,-80,8,NaN,1628899,1631022.0,1611661322,38,40,0,2,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
239,05:47,[WAS] Austin Substitution replaced by Hines-Allen,0,-80,8,NaN,1631022,1628899.0,1611661322,54,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
240,05:47,[WAS] Dolson Substitution replaced by Edwards,0,-80,8,NaN,203828,1642290.0,1611661322,54,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
265,03:29,[WAS] Atkins Substitution replaced by Walker-K...,0,-80,8,NaN,1628878,1628278.0,1611661322,58,51,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
278,02:02,[WAS] Sykes Substitution replaced by Vanloo,0,-80,8,NaN,1628279,1642210.0,1611661322,58,55,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
279,02:02,[WAS] Samuelson Substitution replaced by Atkins,0,-80,8,NaN,1628317,1628878.0,1611661322,58,55,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
283,01:38,[WAS] Hines-Allen Substitution replaced by Austin,0,-80,8,NaN,1628899,1631022.0,1611661322,61,56,0,3,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
311,08:28,[WAS] Austin Substitution replaced by Dolson,0,-80,8,NaN,1631022,203828.0,1611661322,69,64,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
312,08:28,[WAS] Edwards Substitution replaced by Hines-A...,0,-80,8,NaN,1642290,1628899.0,1611661322,69,64,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
325,07:02,[WAS] Walker-Kimbrough Substitution replaced b...,0,-80,8,NaN,1628278,1628317.0,1611661322,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
326,07:02,[WAS] Vanloo Substitution replaced by Sykes,0,-80,8,NaN,1642210,1628279.0,1611661322,71,70,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
368,03:30,[WAS] Hines-Allen Substitution replaced by Austin,0,-80,8,NaN,1628899,1631022.0,1611661322,74,79,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
397,00:16.4,[WAS] Dolson Substitution replaced by Richards,0,-80,8,NaN,203828,1630459.0,1611661322,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
398,00:16.4,[WAS] Samuelson Substitution replaced by Walke...,0,-80,8,NaN,1628317,1628278.0,1611661322,80,81,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
401,00:15.8,[WAS] Richards Substitution replaced by Dolson,0,-80,8,NaN,1630459,203828.0,1611661322,80,82,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
402,00:15.8,[WAS] Walker-Kimbrough Substitution replaced b...,0,-80,8,NaN,1628278,1628317.0,1611661322,80,82,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
405,00:15.8,[WAS] Austin Substitution replaced by Vanloo,0,-80,8,NaN,1631022,1642210.0,1611661322,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
410,00:01.5,[WAS] Samuelson Substitution replaced by Richards,0,-80,8,NaN,1628317,1630459.0,1611661322,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
411,00:01.5,[WAS] Vanloo Substitution replaced by Walker-K...,0,-80,8,NaN,1642210,1628278.0,1611661322,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
412,00:01.5,[WAS] Dolson Substitution replaced by Edwards,0,-80,8,NaN,203828,1642290.0,1611661322,80,83,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313
415,00:00.9,[WAS] Walker-Kimbrough Substitution replaced b...,0,-80,8,NaN,1628278,203828.0,1611661322,80,84,0,4,1628878,1631022,1628279,203828,0,0,0,0,0,0,1611661322,1611661313

In [161]:
for i in list(dfTeam1.index):
    if dfTeam1.loc[i, 'event_type'] == 8:
        if dfTeam1.loc[i, 'player_id'] == dfTeam1.loc[i, 'homePlayer1']:
            dfTeam1.loc[i:, 'homePlayer1'] = dfTeam1.loc[i, 'sec_player_id']
        elif dfTeam1.loc[i, 'player_id'] == dfTeam1.loc[i, 'homePlayer2']:
            dfTeam1.loc[i:, 'homePlayer2'] = dfTeam1.loc[i, 'sec_player_id']
        elif dfTeam1.loc[i, 'player_id'] == dfTeam1.loc[i, 'homePlayer3']:
            dfTeam1.loc[i:, 'homePlayer3'] = dfTeam1.loc[i, 'sec_player_id']
        elif dfTeam1.loc[i, 'player_id'] == dfTeam1.loc[i, 'homePlayer4']:
            dfTeam1.loc[i:, 'homePlayer4'] = dfTeam1.loc[i, 'sec_player_id']
        elif dfTeam1.loc[i, 'player_id'] == dfTeam1.loc[i, 'homePlayer5']:
            dfTeam1.loc[i:, 'homePlayer5'] = dfTeam1.loc[i, 'sec_player_id']
        else:
            if dfTeam1.loc[i, 'homePlayer1'] == 0:
                dfTeam1.loc[:i, 'homePlayer1'] = dfTeam1.loc[i, 'player_id']
                dfTeam1.loc[i:, 'homePlayer1'] = dfTeam1.loc[i, 'sec_player_id']
            if dfTeam1.loc[i, 'homePlayer2'] == 0:
                dfTeam1.loc[:i, 'homePlayer2'] = dfTeam1.loc[i, 'player_id']
                dfTeam1.loc[i:, 'homePlayer2'] = dfTeam1.loc[i, 'sec_player_id']
            if dfTeam1.loc[i, 'homePlayer3'] == 0:
                dfTeam1.loc[:i, 'homePlayer3'] = dfTeam1.loc[i, 'player_id']
                dfTeam1.loc[i:, 'homePlayer3'] = dfTeam1.loc[i, 'sec_player_id']
            if dfTeam1.loc[i, 'homePlayer4'] == 0:
                dfTeam1.loc[:i, 'homePlayer4'] = dfTeam1.loc[i, 'player_id']
                dfTeam1.loc[i:, 'homePlayer4'] = dfTeam1.loc[i, 'sec_player_id']
            if dfTeam1.loc[i, 'homePlayer5'] == 0:
                dfTeam1.loc[:i, 'homePlayer5'] = dfTeam1.loc[i, 'player_id']
                dfTeam1.loc[i:, 'homePlayer5'] = dfTeam1.loc[i, 'sec_player_id']

dfTeam1.iloc[:, 9:]

,home_score,away_score,points,period,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,awayPlayer1,awayPlayer2,awayPlayer3,awayPlayer4,awayPlayer5,homeTeam,awayTeam
3,0,0,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
6,2,2,2,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
8,2,2,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
11,5,4,3,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
16,5,4,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
18,5,4,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
21,8,6,3,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
23,11,8,3,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
25,11,8,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
26,11,8,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
29,13,10,2,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
31,13,10,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
32,13,10,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
33,13,10,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
34,13,10,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
37,13,13,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
40,13,13,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
43,13,13,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
46,13,13,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
49,15,13,2,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
51,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
52,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
54,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
57,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
58,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
59,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
60,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
61,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
62,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313
63,15,16,0,1,1642210,1628899,1628279,1642290,1628317,0,0,0,0,0,1611661322,1611661313
67,15,18,0,1,1642210,1628899,1628278,1642290,1628317,0,0,0,0,0,1611661322,1611661313
68,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
69,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
72,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
73,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
74,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
77,18,20,3,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
79,20,23,2,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
80,20,23,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
81,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
87,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
89,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
90,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
91,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
94,20,23,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
96,20,23,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
98,22,25,2,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
100,22,27,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
101,22,27,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
103,22,27,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
107,22,27,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
111,23,27,1,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
112,24,27,1,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
114,24,29,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
115,24,29,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
116,24,29,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
120,24,31,0,2,1642210,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
121,24,31,0,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
124,25,31,1,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
125,26,31,1,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
127,26,31,0,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
128,26,31,0,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
130,26,31,0,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
131,28,31,2,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313
133,28,31,0,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313
137,28,31,0,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313
139,28,31,0,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313
142,30,34,2,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313
143,30,34,0,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313
144,30,34,0,2,203828,1628279,1628278,1628899,1628317,0,0,0,0,0,1611661322,1611661313
145,30,34,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
147,30,36,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
149,30,36,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
152,30,36,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
154,30,38,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
155,30,38,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
157,30,39,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
161,30,39,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
164,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
165,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
167,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
169,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
170,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313
171,30,40,0,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
173,31,40,1,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
175,33,40,2,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
177,35,40,2,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
179,35,40,0,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
180,35,40,0,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
183,35,40,0,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
184,38,40,3,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
186,38,40,0,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
191,38,40,0,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
193,39,40,1,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
195,40,40,1,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
200,40,40,0,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
201,43,40,3,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
207,43,40,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
209,43,40,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
211,43,42,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
213,43,43,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
218,45,43,2,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
220,45,46,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
223,45,46,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
224,48,46,3,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
228,48,46,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
229,50,46,2,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
231,52,48,2,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
233,52,48,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
234,54,48,2,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
236,54,51,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
237,54,51,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313
239,54,51,0,3,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
240,54,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
241,54,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
244,54,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
245,56,51,2,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
248,56,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
251,58,51,2,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
255,58,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
256,58,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
259,58,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
260,58,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
264,58,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313
265,58,51,0,3,1642290,1628279,1628278,1628899,1628317,0,0,0,0,0,1611661322,1611661313
269,58,51,0,3,1642290,1628279,1628278,1628899,1628317,0,0,0,0,0,1611661322,1611661313
270,58,51,0,3,1642290,1628279,1628278,1628899,1628317,0,0,0,0,0,1611661322,1611661313
273,58,53,0,3,1642290,1628279,1628278,1628899,1628317,0,0,0,0,0,1611661322,1611661313
278,58,55,0,3,1642290,1642210,1628278,1628899,1628317,0,0,0,0,0,1611661322,1611661313
279,58,55,0,3,1642290,1642210,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313
280,61,55,3,3,1642290,1642210,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313
281,61,55,0,3,1642290,1642210,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313
283,61,56,0,3,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
286,61,57,0,3,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
288,64,59,3,3,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
290,64,59,0,3,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
291,64,59,0,3,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
292,64,59,0,3,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
296,67,59,3,3,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
300,67,59,0,4,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
302,67,59,0,4,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
304,67,59,0,4,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
306,69,61,2,4,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
308,69,64,0,4,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
309,69,64,0,4,1642290,1642210,1628278,1631022,1628878,0,0,0,0,0,1611661322,1611661313
311,69,64,0,4,1642290,1642210,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
312,69,64,0,4,1628899,1642210,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
313,69,64,0,4,1628899,1642210,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
316,69,64,0,4,1628899,1642210,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
319,69,65,0,4,1628899,1642210,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
320,71,65,2,4,1628899,1642210,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
322,71,68,0,4,1628899,1642210,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
324,71,70,0,4,1628899,1642210,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
325,71,70,0,4,1628899,1642210,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
326,71,70,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
327,71,70,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
330,71,70,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
333,71,70,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
334,71,70,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
335,71,70,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
336,71,70,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
338,71,70,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
340,71,72,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
341,71,72,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
345,71,74,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
347,71,75,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
348,71,75,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
350,71,75,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
351,71,75,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
352,72,75,1,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
355,72,75,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
356,72,75,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
361,74,77,2,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
362,74,77,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
364,74,77,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
365,74,77,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
367,74,79,0,4,1628899,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
368,74,79,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
369,74,79,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
371,76,81,2,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
374,78,81,2,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
378,80,81,2,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
380,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
381,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
386,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
389,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
390,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
391,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
392,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
393,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
394,80,81,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
397,80,81,0,4,1631022,1628279,1628317,1630459,1628878,0,0,0,0,0,1611661322,1611661313
398,80,81,0,4,1631022,1628279,1628278,1630459,1628878,0,0,0,0,0,1611661322,1611661313
399,80,81,0,4,1631022,1628279,1628278,1630459,1628878,0,0,0,0,0,1611661322,1611661313
401,80,82,0,4,1631022,1628279,1628278,203828,1628878,0,0,0,0,0,1611661322,1611661313
402,80,82,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
404,80,83,0,4,1631022,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
405,80,83,0,4,1642210,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
406,80,83,0,4,1642210,1628279,1628317,203828,1628878,0,0,0,0,0,1611661322,1611661313
410,80,83,0,4,1642210,1628279,1630459,203828,1628878,0,0,0,0,0,1611661322,1611661313
411,80,83,0,4,1628278,1628279,1630459,203828,1628878,0,0,0,0,0,1611661322,1611661313
412,80,83,0,4,1628278,1628279,1630459,1642290,1628878,0,0,0,0,0,1611661322,1611661313
413,80,83,0,4,1628278,1628279,1630459,1642290,1628878,0,0,0,0,0,1611661322,1611661313
415,80,84,0,4,203828,1628279,1630459,1642290,1628878,0,0,0,0,0,1611661322,1611661313

In [177]:
HP1 = dfTeam1.loc[3, 'homePlayer1']
HP2 = dfTeam1.loc[3, 'homePlayer2']
HP3 = dfTeam1.loc[3, 'homePlayer3']
HP4 = dfTeam1.loc[3, 'homePlayer4']
HP5 = dfTeam1.loc[3, 'homePlayer5']
dfTeam1['lineupPlusMinus'] = 0
startingDifferential = 0

for ind, i in enumerate(list(dfTeam1.index)):
    if (dfTeam1.loc[i, 'homePlayer1'] != HP1) | (dfTeam1.loc[i, 'homePlayer2'] != HP2) | (dfTeam1.loc[i, 'homePlayer3'] != HP3) | (dfTeam1.loc[i, 'homePlayer4'] != HP4) | (dfTeam1.loc[i, 'homePlayer5'] != HP5):
        dfTeam1.loc[list(dfTeam1.index)[ind - 1], 'lineupPlusMinus'] = (dfTeam1.loc[i, 'home_score'] - dfTeam1.loc[i, 'away_score']) - startingDifferential
        startingDifferential = dfTeam1.loc[i, 'home_score'] - dfTeam1.loc[i, 'away_score']
        if (dfTeam1.loc[i, 'homePlayer1'] != HP1):
            HP1 = dfTeam1.loc[i, 'homePlayer1']
        elif (dfTeam1.loc[i, 'homePlayer2'] != HP2):
            HP2 = dfTeam1.loc[i, 'homePlayer2']
        elif (dfTeam1.loc[i, 'homePlayer3'] != HP3):
            HP3 = dfTeam1.loc[i, 'homePlayer3']
        elif (dfTeam1.loc[i, 'homePlayer4'] != HP4):
            HP4 = dfTeam1.loc[i, 'homePlayer4']
        elif (dfTeam1.loc[i, 'homePlayer5'] != HP5):
            HP5 = dfTeam1.loc[i, 'homePlayer5']

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_17992/3338932683.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTeam1['lineupPlusMinus'] = 0

In [179]:
dfTeam1

,game_clock,description,location_x,location_y,event_type,opp_player_id,player_id,sec_player_id,team_id,home_score,away_score,points,period,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,awayPlayer1,awayPlayer2,awayPlayer3,awayPlayer4,awayPlayer5,homeTeam,awayTeam,lineupPlusMinus
3,09:45,[WAS] Atkins Pullup Jump shot: Missed,-135,35,2,NaN,1628878,NaN,1611661322,0,0,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
6,09:19,[WAS 2-2] Austin Driving Layup Shot: Made (2 P...,-49,24,1,NaN,1631022,1628279.0,1611661322,2,2,2,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
8,09:19,[WAS] Austin Free Throw 1 of 1 Missed,0,-80,3,NaN,1631022,NaN,1611661322,2,2,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
11,08:58,[WAS 5-4] Atkins 3pt Shot: Made (3 PTS) Assist...,-238,-42,1,NaN,1628878,203828.0,1611661322,5,4,3,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
16,08:33,[WAS] Austin Rebound (Off:0 Def:1),2,49,4,NaN,1631022,NaN,1611661322,5,4,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
18,08:22,[WAS] Sykes 3pt Shot: Missed,170,202,2,NaN,1628279,NaN,1611661322,5,4,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
21,07:50,[WAS 8-6] Dolson 3pt Shot: Made (3 PTS) Assist...,-174,157,1,NaN,203828,1628279.0,1611661322,8,6,3,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
23,07:14,[WAS 11-8] Dolson 3pt Shot: Made (6 PTS) Assis...,-222,48,1,NaN,203828,1628878.0,1611661322,11,8,3,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
25,06:54,[WAS] Dolson Rebound (Off:0 Def:1),-99,16,4,NaN,203828,NaN,1611661322,11,8,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
26,06:46,[WAS] Dolson 3pt Shot: Missed,-89,225,2,NaN,203828,NaN,1611661322,11,8,0,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
29,06:12,[WAS 13-10] Austin Pullup Jump shot: Made (4 P...,89,137,1,NaN,1631022,1628279.0,1611661322,13,10,2,1,1628878,1631022,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,3
31,06:00,[WAS] Austin Substitution replaced by Hines-Allen,0,-80,8,NaN,1631022,1628899.0,1611661322,13,10,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
32,05:47,[WAS] Samuelson Driving Layup Shot: Missed,-23,37,2,NaN,1628317,NaN,1611661322,13,10,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
33,05:43,[WAS] Hines-Allen Rebound (Off:1 Def:0),-23,37,4,NaN,1628899,NaN,1611661322,13,10,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
34,05:37,[WAS] Sykes Pullup Jump shot: Missed,106,144,2,NaN,1628279,NaN,1611661322,13,10,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
37,05:10,[WAS] Samuelson Driving Layup Shot: Missed,79,20,2,NaN,1628317,NaN,1611661322,13,13,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
40,04:56,[WAS] Sykes Rebound (Off:0 Def:1),9,23,4,NaN,1628279,NaN,1611661322,13,13,0,1,1628878,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,-3
43,04:53,[WAS] Atkins Substitution replaced by Vanloo,0,-80,8,NaN,1628878,1642210.0,1611661322,13,13,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
46,04:46,[WAS] Samuelson 3pt Shot: Missed,243,16,2,NaN,1628317,NaN,1611661322,13,13,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
49,04:31,[WAS 15-13] Sykes Running Layup Shot: Made (2 ...,13,14,1,NaN,1628279,NaN,1611661322,15,13,2,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
51,03:58,[WAS] Hines-Allen Layup Shot: Missed Block: Sa...,51,-13,2,1631055.0,1628899,NaN,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
52,03:58,[WAS] Team Rebound,51,-13,4,NaN,0,NaN,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
54,03:50,[WAS] Hines-Allen Cutting Layup Shot: Missed,0,3,2,NaN,1628899,NaN,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
57,03:28,[WAS] Hines-Allen 3pt Shot: Missed,93,220,2,NaN,1628899,NaN,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
58,03:25,[WAS] Sykes Rebound (Off:1 Def:1),93,220,4,NaN,1628279,NaN,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
59,03:23,[WAS] Sykes Putback Layup Shot: Missed,54,3,2,NaN,1628279,NaN,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
60,03:23,[WAS] Samuelson Rebound (Off:1 Def:0),54,3,4,NaN,1628317,NaN,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
61,03:13,[WAS] Vanloo Turnover : Lost Ball (1 TO) Steal...,94,204,5,204335.0,1642210,NaN,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,0
62,03:13,[WAS] Vanloo Foul: Personal (1 PF),-4,501,6,204335.0,1642210,202297.0,1611661322,15,16,0,1,1642210,1628899,1628279,203828,1628317,0,0,0,0,0,1611661322,1611661313,-1
63,03:13,[WAS] Dolson Substitution replaced by Edwards,0,-80,8,NaN,203828,1642290.0,1611661322,15,16,0,1,1642210,1628899,1628279,1642290,1628317,0,0,0,0,0,1611661322,1611661313,-2
67,02:42,[WAS] Sykes Substitution replaced by Walker-Ki...,0,-80,8,NaN,1628279,1628278.0,1611661322,15,18,0,1,1642210,1628899,1628278,1642290,1628317,0,0,0,0,0,1611661322,1611661313,0
68,02:42,[WAS] Samuelson Substitution replaced by Atkins,0,-80,8,NaN,1628317,1628878.0,1611661322,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
69,02:32,[WAS] Atkins 3pt Shot: Missed,-104,262,2,NaN,1628878,NaN,1611661322,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
72,02:03,[WAS] Vanloo 3pt Shot: Missed Block: Ionescu (...,-182,143,2,1629477.0,1642210,NaN,1611661322,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
73,02:02,[WAS] Edwards Rebound (Off:1 Def:0),-182,143,4,NaN,1642290,NaN,1611661322,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
74,01:56,[WAS] Edwards Jump Shot: Missed,-7,-13,2,NaN,1642290,NaN,1611661322,15,18,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
77,01:33,[WAS 18-20] Hines-Allen 3pt Shot: Made (3 PTS)...,51,231,1,NaN,1628899,1642210.0,1611661322,18,20,3,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
79,01:01,[WAS 20-23] Atkins Driving Floating Jump Shot:...,-100,30,1,NaN,1628878,1628899.0,1611661322,20,23,2,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
80,00:51.7,[WAS] Walker-Kimbrough Foul: Personal (1 PF),77,91,6,1631055.0,1628278,1629177.0,1611661322,20,23,0,1,1642210,1628899,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
81,00:51.7,[WAS] Hines-Allen Substitution replaced by Austin,0,-80,8,NaN,1628899,1631022.0,1611661322,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
87,00:18.0,[WAS] Atkins Turnover : Bad Pass (1 TO) Steal:...,10,287,5,1630142.0,1628878,NaN,1611661322,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
89,00:00.9,[WAS] Edwards Rebound (Off:1 Def:1),73,39,4,NaN,1642290,NaN,1611661322,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
90,00:00.2,[WAS] Walker-Kimbrough Driving Layup Shot: Mis...,49,-10,2,203866.0,1628278,NaN,1611661322,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
91,00:00.1,[WAS] Team Rebound,49,-10,4,NaN,0,NaN,1611661322,20,23,0,1,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
94,09:44,[WAS] Atkins 3pt Shot: Missed,-196,133,2,NaN,1628878,NaN,1611661322,20,23,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
96,09:32,[WAS] Edwards Foul: Personal (1 PF),-60,66,6,1627668.0,1642290,202764.0,1611661322,20,23,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
98,09:12,[WAS 22-25] Austin Cutting Layup Shot: Made (6...,-28,-7,1,NaN,1631022,1642210.0,1611661322,22,25,2,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
100,08:38,[WAS] Walker-Kimbrough Pullup Jump shot: Missed,81,167,2,NaN,1628278,NaN,1611661322,22,27,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
101,08:35,[WAS] Team Rebound,81,167,4,NaN,0,NaN,1611661322,22,27,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
103,08:29,[WAS] Austin Layup Shot: Missed,-7,31,2,NaN,1631022,NaN,1611661322,22,27,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
107,08:20,[WAS] Vanloo 3pt Shot: Missed,-219,52,2,NaN,1642210,NaN,1611661322,22,27,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
111,08:14,[WAS 23-27] Atkins Free Throw 1 of 2 (6 PTS),0,-80,3,NaN,1628878,NaN,1611661322,23,27,1,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
112,08:14,[WAS 24-27] Atkins Free Throw 2 of 2 (7 PTS),0,-80,3,NaN,1628878,NaN,1611661322,24,27,1,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
114,07:44,[WAS] Edwards Driving Layup Shot: Missed,55,25,2,NaN,1642290,NaN,1611661322,24,29,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
115,07:43,[WAS] Austin Rebound (Off:1 Def:1),55,25,4,NaN,1631022,NaN,1611661322,24,29,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
116,07:42,[WAS] Austin Putback Layup Shot: Missed,42,11,2,NaN,1631022,NaN,1611661322,24,29,0,2,1642210,1631022,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,-4
120,07:20,[WAS] Austin Substitution replaced by Sykes,0,-80,8,NaN,1631022,1628279.0,1611661322,24,31,0,2,1642210,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
121,07:20,[WAS] Vanloo Substitution replaced by Dolson,0,-80,8,NaN,1642210,203828.0,1611661322,24,31,0,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
124,07:14,[WAS 25-31] Edwards Free Throw 1 of 2 (1 PTS),0,-80,3,NaN,1642290,NaN,1611661322,25,31,1,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
125,07:14,[WAS 26-31] Edwards Free Throw 2 of 2 (2 PTS),0,-80,3,NaN,1642290,NaN,1611661322,26,31,1,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
127,06:47,[WAS] Sykes Rebound (Off:1 Def:2),-67,183,4,NaN,1628279,NaN,1611661322,26,31,0,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
128,06:46,[WAS] Sykes Turnover : Out of Bounds - Bad Pas...,156,377,5,NaN,1628279,202297.0,1611661322,26,31,0,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
130,06:26,[WAS] Sykes Rebound (Off:1 Def:3),-212,233,4,NaN,1628279,NaN,1611661322,26,31,0,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,0
131,06:17,[WAS 28-31] Dolson Layup Shot: Made (8 PTS) As...,29,-16,1,NaN,203828,1628279.0,1611661322,28,31,2,2,203828,1628279,1628278,1642290,1628878,0,0,0,0,0,1611661322,1611661313,4
133,06:17,[WAS] Edwards Substitution replaced by Hines-A...,0,-80,8,NaN,1642290,1628899.0,1611661322,28,31,0,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313,0
137,06:01,[WAS] Sykes Rebound (Off:1 Def:4),-235,22,4,NaN,1628279,NaN,1611661322,28,31,0,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313,0
139,05:43,[WAS] Atkins Jump Shot: Missed,77,48,2,NaN,1628878,NaN,1611661322,28,31,0,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313,0
142,05:12,[WAS 30-34] Hines-Allen Layup Shot: Made (5 PT...,-22,-5,1,NaN,1628899,1628279.0,1611661322,30,34,2,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313,0
143,05:04,[WAS] Dolson Foul: Personal (1 PF),-63,-4,6,1627673.0,203828,202764.0,1611661322,30,34,0,2,203828,1628279,1628278,1628899,1628878,0,0,0,0,0,1611661322,1611661313,-1
144,05:04,[WAS] Atkins Substitution replaced by Samuelson,0,-80,8,NaN,1628878,1628317.0,1611661322,30,34,0,2,203828,1628279,1628278,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
145,05:04,[WAS] Walker-Kimbrough Substitution replaced b...,0,-80,8,NaN,1628278,1630459.0,1611661322,30,34,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
147,04:39,[WAS] Sykes 3pt Shot: Missed,-197,133,2,NaN,1628279,NaN,1611661322,30,36,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
149,04:31,[WAS] Hines-Allen Foul: Personal (1 PF),-50,42,6,1627673.0,1628899,202297.0,1611661322,30,36,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
152,04:12,[WAS] Sykes Foul: Personal (1 PF),44,163,6,1627673.0,1628279,1629177.0,1611661322,30,36,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
154,04:07,[WAS] Hines-Allen Foul: Shooting (2 PF) (1 FTA),0,148,6,1629477.0,1628899,1629177.0,1611661322,30,38,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
155,04:07,Timeout : Regular,0,-80,9,NaN,1611661322,NaN,1611661322,30,38,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
157,03:51,[WAS] Richards Pullup Jump shot: Missed,53,84,2,NaN,1630459,NaN,1611661322,30,39,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
161,03:37,[WAS] Sykes Foul: Personal (2 PF) (2 FTA),55,26,6,1641602.0,1628279,202297.0,1611661322,30,39,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
164,03:35,[WAS] Sykes Rebound (Off:1 Def:5),0,-80,4,NaN,1628279,NaN,1611661322,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
165,03:24,[WAS] Samuelson Turnover : Lost Ball (1 TO) St...,-40,27,5,1641602.0,1628317,NaN,1611661322,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
167,03:04,[WAS] Samuelson Rebound (Off:1 Def:1),197,180,4,NaN,1628317,NaN,1611661322,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
169,02:58,[WAS] Dolson Free Throw 1 of 2 Missed,0,-80,3,NaN,203828,NaN,1611661322,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
170,02:58,[WAS] Team Rebound,0,-80,4,NaN,0,NaN,1611661322,30,40,0,2,203828,1628279,1630459,1628899,1628317,0,0,0,0,0,1611661322,1611661313,-6
171,02:58,[WAS] Richards Substitution replaced by Atkins,0,-80,8,NaN,1630459,1628878.0,1611661322,30,40,0,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
173,02:58,[WAS 31-40] Dolson Free Throw 2 of 2 (9 PTS),0,-80,3,NaN,203828,NaN,1611661322,31,40,1,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
175,02:39,[WAS 33-40] Dolson Jump Shot: Made (11 PTS) As...,-68,149,1,NaN,203828,1628878.0,1611661322,33,40,2,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
177,02:23,[WAS 35-40] Sykes Running Layup Shot: Made (4 ...,26,-11,1,NaN,1628279,1628878.0,1611661322,35,40,2,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
179,02:05,[WAS] Hines-Allen Rebound (Off:1 Def:1),236,-3,4,NaN,1628899,NaN,1611661322,35,40,0,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
180,01:49,[WAS] Atkins Floating Jump shot: Missed,-34,32,2,NaN,1628878,NaN,1611661322,35,40,0,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
183,01:38,[WAS] Dolson Rebound (Off:0 Def:2),106,225,4,NaN,203828,NaN,1611661322,35,40,0,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
184,01:27,[WAS 38-40] Samuelson 3pt Shot: Made (3 PTS) A...,-230,-26,1,NaN,1628317,1628279.0,1611661322,38,40,3,2,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,8
186,01:26,[WAS] Hines-Allen Substitution replaced by Austin,0,-80,8,NaN,1628899,1631022.0,1611661322,38,40,0,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
191,01:05,[WAS] Samuelson Rebound (Off:1 Def:2),17,17,4,NaN,1628317,NaN,1611661322,38,40,0,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
193,00:50.5,[WAS 39-40] Samuelson Free Throw 1 of 2 (4 PTS),0,-80,3,NaN,1628317,NaN,1611661322,39,40,1,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
195,00:50.5,[WAS 40-40] Samuelson Free Throw 2 of 2 (5 PTS),0,-80,3,NaN,1628317,NaN,1611661322,40,40,1,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
200,00:28.0,[WAS] Austin Rebound (Off:1 Def:2),-27,286,4,NaN,1631022,NaN,1611661322,40,40,0,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
201,00:05.6,[WAS 43-40] Austin 3pt Shot: Made (9 PTS) Assi...,-207,127,1,NaN,1631022,1628317.0,1611661322,43,40,3,2,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
207,09:42,[WAS] Sykes 3pt Shot: Missed,232,-8,2,NaN,1628279,NaN,1611661322,43,40,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
209,09:28,[WAS] Samuelson Foul: Personal (1 PF),188,92,6,1627668.0,1628317,202764.0,1611661322,43,40,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
211,09:21,[WAS] Atkins Foul: Shooting (1 PF) (1 FTA),-5,33,6,1629477.0,1628878,1629177.0,1611661322,43,42,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
213,09:10,[WAS] Sykes Driving Layup Shot: Missed Block: ...,-73,35,2,1627673.0,1628279,NaN,1611661322,43,43,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
218,08:48,[WAS 45-43] Atkins Driving Layup Shot: Made (9...,-67,26,1,NaN,1628878,1631022.0,1611661322,45,43,2,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
220,08:27,[WAS] Sykes Finger Roll Layup Shot: Missed,5,40,2,NaN,1628279,NaN,1611661322,45,46,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
223,08:13,[WAS] Austin Rebound (Off:1 Def:3),121,223,4,NaN,1631022,NaN,1611661322,45,46,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
224,08:06,[WAS 48-46] Atkins 3pt Shot: Made (12 PTS) Ass...,125,204,1,NaN,1628878,1631022.0,1611661322,48,46,3,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
228,07:37,[WAS] Dolson Rebound (Off:0 Def:3),51,-23,4,NaN,203828,NaN,1611661322,48,46,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
229,07:23,[WAS 50-46] Samuelson Driving Layup Shot: Made...,18,22,1,NaN,1628317,NaN,1611661322,50,46,2,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
231,06:51,[WAS 52-48] Austin Driving Bank Hook Shot: Mad...,41,28,1,NaN,1631022,NaN,1611661322,52,48,2,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
233,06:40,[WAS] Samuelson Rebound (Off:1 Def:3),44,80,4,NaN,1628317,NaN,1611661322,52,48,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
234,06:30,[WAS 54-48] Sykes Hook Shot: Made (6 PTS),-33,10,1,NaN,1628279,NaN,1611661322,54,48,2,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
236,05:49,[WAS] Austin Pullup Jump shot: Missed,-28,173,2,NaN,1631022,NaN,1611661322,54,51,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,0
237,05:47,[WAS] Team Rebound,-28,173,4,NaN,0,NaN,1611661322,54,51,0,3,203828,1628279,1628878,1631022,1628317,0,0,0,0,0,1611661322,1611661313,5
239,05:47,[WAS] Austin Substitution replaced by Hines-Allen,0,-80,8,NaN,1631022,1628899.0,1611661322,54,51,0,3,203828,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0
240,05:47,[WAS] Dolson Substitution replaced by Edwards,0,-80,8,NaN,203828,1642290.0,1611661322,54,51,0,3,1642290,1628279,1628878,1628899,1628317,0,0,0,0,0,1611661322,1611661313,0

In [181]:
imptCols = ['homePlayer1', 'homePlayer2', 'homePlayer3', 'homePlayer4', 'homePlayer5', 'lineupPlusMinus']
imptIndex = []
for ind, i in enumerate(list(dfTeam1.index)):
    if dfTeam1.loc[i, 'event_type'] == 8:
        imptIndex.append(list(dfTeam1.index)[ind - 1])

homeTeamLineups = dfTeam1.loc[imptIndex, imptCols]
homeTeamLineups

,homePlayer1,homePlayer2,homePlayer3,homePlayer4,homePlayer5,lineupPlusMinus
29,1628878,1631022,1628279,203828,1628317,3
40,1628878,1628899,1628279,203828,1628317,-3
62,1642210,1628899,1628279,203828,1628317,-1
63,1642210,1628899,1628279,1642290,1628317,-2
67,1642210,1628899,1628278,1642290,1628317,0
80,1642210,1628899,1628278,1642290,1628878,0
116,1642210,1631022,1628278,1642290,1628878,-4
120,1642210,1628279,1628278,1642290,1628878,0
131,203828,1628279,1628278,1642290,1628878,4
143,203828,1628279,1628278,1628899,1628878,-1
144,203828,1628279,1628278,1628899,1628317,0
170,203828,1628279,1630459,1628899,1628317,-6
184,203828,1628279,1628878,1628899,1628317,8
237,203828,1628279,1628878,1631022,1628317,5
239,203828,1628279,1628878,1628899,1628317,0
264,1642290,1628279,1628878,1628899,1628317,4
273,1642290,1628279,1628278,1628899,1628317,-4
278,1642290,1642210,1628278,1628899,1628317,0
281,1642290,1642210,1628278,1628899,1628878,2
309,1642290,1642210,1628278,1631022,1628878,0
311,1642290,1642210,1628278,203828,1628878,0
324,1628899,1642210,1628278,203828,1628878,-4
325,1628899,1642210,1628317,203828,1628878,0
367,1628899,1628279,1628317,203828,1628878,-6
394,1631022,1628279,1628317,203828,1628878,4
397,1631022,1628279,1628317,1630459,1628878,0
399,1631022,1628279,1628278,1630459,1628878,-1
401,1631022,1628279,1628278,203828,1628878,0
404,1631022,1628279,1628317,203828,1628878,-1
406,1642210,1628279,1628317,203828,1628878,0
410,1642210,1628279,1630459,203828,1628878,0
411,1628278,1628279,1630459,203828,1628878,0
413,1628278,1628279,1630459,1642290,1628878,-1

In [183]:
def getPlayersHome(dataframe):
    alreadyScenePlayerHome = []
    for playerID in dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['player_id']:
        if playerID not in alreadyScenePlayer:
            if (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['homePlayer1'] == 0).any():
                dataframe['homePlayer1'] = playerID
            elif (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['homePlayer2'] == 0).any():
                dataframe['homePlayer2'] = playerID
            elif (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['homePlayer3'] == 0).any():
                dataframe['homePlayer3'] = playerID
            elif (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['homePlayer4'] == 0).any():
                dataframe['homePlayer4'] = playerID
            elif (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['homePlayer5'] == 0).any():
                dataframe['homePlayer5'] = playerID

            alreadyScenePlayerHome.append(playerID)

In [ ]:
def getPlayersAway(dataframe):
    alreadyScenePlayerAway = []
    for playerID in dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['player_id']:
        if playerID not in alreadyScenePlayer:
            if (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['awayPlayer1'] == 0).any():
                dataframe['awayPlayer1'] = playerID
            elif (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['awayPlayer2'] == 0).any():
                dataframe['awayPlayer2'] = playerID
            elif (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['awayPlayer3'] == 0).any():
                dataframe['awayPlayer3'] = playerID
            elif (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['awayPlayer4'] == 0).any():
                dataframe['awayPlayer4'] = playerID
            elif (dataframe.loc[:list(dataframe[dataframe['event_type'] == 8].index)[0] - 1, :]['awayPlayer5'] == 0).any():
                dataframe['awayPlayer5'] = playerID

            alreadyScenePlayerAway.append(playerID)

In [187]:
def getSubsHome(dataframe):
    
    for i in list(dataframe.index):
        if dataframe.loc[i, 'event_type'] == 8:
            if dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer1']:
                dataframe.loc[i:, 'homePlayer1'] = dataframe.loc[i, 'sec_player_id']
            elif dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer2']:
                dataframe.loc[i:, 'homePlayer2'] = dataframe.loc[i, 'sec_player_id']
            elif dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer3']:
                dataframe.loc[i:, 'homePlayer3'] = dataframe.loc[i, 'sec_player_id']
            elif dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer4']:
                dataframe.loc[i:, 'homePlayer4'] = dataframe.loc[i, 'sec_player_id']
            elif dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer5']:
                dataframe.loc[i:, 'homePlayer5'] = dataframe.loc[i, 'sec_player_id']
            else:
                if dataframe.loc[i, 'homePlayer1'] == 0:
                    dataframe.loc[:i, 'homePlayer1'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer1'] = dataframe.loc[i, 'sec_player_id']
                if dataframe.loc[i, 'homePlayer2'] == 0:
                    dataframe.loc[:i, 'homePlayer2'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer2'] = dataframe.loc[i, 'sec_player_id']
                if dataframe.loc[i, 'homePlayer3'] == 0:
                    dataframe.loc[:i, 'homePlayer3'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer3'] = dataframe.loc[i, 'sec_player_id']
                if dataframe.loc[i, 'homePlayer4'] == 0:
                    dataframe.loc[:i, 'homePlayer4'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer4'] = dataframe.loc[i, 'sec_player_id']
                if dataframe.loc[i, 'homePlayer5'] == 0:
                    dataframe.loc[:i, 'homePlayer5'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer5'] = dataframe.loc[i, 'sec_player_id']

In [ ]:
def getSubsHome(dataframe):
    
    for i in list(dataframe.index):
        if dataframe.loc[i, 'event_type'] == 8:
            if dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer1']:
                dataframe.loc[i:, 'homePlayer1'] = dataframe.loc[i, 'sec_player_id']
            elif dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer2']:
                dataframe.loc[i:, 'homePlayer2'] = dataframe.loc[i, 'sec_player_id']
            elif dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer3']:
                dataframe.loc[i:, 'homePlayer3'] = dataframe.loc[i, 'sec_player_id']
            elif dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer4']:
                dataframe.loc[i:, 'homePlayer4'] = dataframe.loc[i, 'sec_player_id']
            elif dataframe.loc[i, 'player_id'] == dataframe.loc[i, 'homePlayer5']:
                dataframe.loc[i:, 'homePlayer5'] = dataframe.loc[i, 'sec_player_id']
            else:
                if dataframe.loc[i, 'homePlayer1'] == 0:
                    dataframe.loc[:i, 'homePlayer1'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer1'] = dataframe.loc[i, 'sec_player_id']
                if dataframe.loc[i, 'homePlayer2'] == 0:
                    dataframe.loc[:i, 'homePlayer2'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer2'] = dataframe.loc[i, 'sec_player_id']
                if dataframe.loc[i, 'homePlayer3'] == 0:
                    dataframe.loc[:i, 'homePlayer3'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer3'] = dataframe.loc[i, 'sec_player_id']
                if dataframe.loc[i, 'homePlayer4'] == 0:
                    dataframe.loc[:i, 'homePlayer4'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer4'] = dataframe.loc[i, 'sec_player_id']
                if dataframe.loc[i, 'homePlayer5'] == 0:
                    dataframe.loc[:i, 'homePlayer5'] = dataframe.loc[i, 'player_id']
                    dataframe.loc[i:, 'homePlayer5'] = dataframe.loc[i, 'sec_player_id']

In [ ]:
def getPlusMinusHome(dataframe):
    P1 = dataframe.loc[list(dataframe.index)[0], 'homePlayer1']
    P2 = dataframe.loc[list(dataframe.index)[0], 'homePlayer2']
    P3 = dataframe.loc[list(dataframe.index)[0], 'homePlayer3']
    P4 = dataframe.loc[list(dataframe.index)[0], 'homePlayer4']
    P5 = dataframe.loc[list(dataframe.index)[0], 'homePlayer5']
    dataframe['lineupPlusMinus'] = 0
    startingDifferential = 0

    for ind, i in enumerate(list(dataframe.index)):
        if (dataframe.loc[i, 'homePlayer1'] != P1) | (dataframe.loc[i, 'homePlayer2'] != P2) | (dataframe.loc[i, 'homePlayer3'] != P3) | (dataframe.loc[i, 'homePlayer4'] != P4) | (dataframe.loc[i, 'homePlayer5'] != P5):
            dataframe.loc[list(dataframe.index)[ind - 1], 'lineupPlusMinus'] = (dataframe.loc[i, 'home_score'] - dataframe.loc[i, 'away_score']) - startingDifferential
            startingDifferential = dataframe.loc[i, 'home_score'] - dataframe.loc[i, 'away_score']
            if (dataframe.loc[i, 'homePlayer1'] != P1):
                P1 = dataframe.loc[i, 'homePlayer1']
            elif (dataframe.loc[i, 'homePlayer2'] != P2):
                P2 = dataframe.loc[i, 'homePlayer2']
            elif (dataframe.loc[i, 'homePlayer3'] != P3):
                P3 = dataframe.loc[i, 'homePlayer3']
            elif (dataframe.loc[i, 'homePlayer4'] != P4):
                P4 = dataframe.loc[i, 'homePlayer4']
            elif (dataframe.loc[i, 'homePlayer5'] != P5):
                P5 = dataframe.loc[i, 'homePlayer5']

In [ ]:
def getLineups2024(gameID)

#read in df
df = pd.read_csv('2024 pbp 11.40.43â€¯AM/wnba_playbyplay_1022400001.csv')

# create lineups
df['homePlayer1'] = 0
df['homePlayer2'] = 0
df['homePlayer3'] = 0
df['homePlayer4'] = 0
df['homePlayer5'] = 0
df['awayPlayer1'] = 0
df['awayPlayer2'] = 0
df['awayPlayer3'] = 0
df['awayPlayer4'] = 0
df['awayPlayer5'] = 0

df['homeTeam'] = df.loc[list(df[df['home_score'] != 0].index)[0], 'team_id']
df['awayTeam'] = df.loc[list(df[df['away_score'] != 0].index)[0], 'team_id']

home = df[df['team_id'] == df['homeTeam']]
away = df[df['team_id'] == df['awayTeam']]

getPlayers(home)
getPlayers(away)

getSubs(home)
getSubs(away)